# Generated by Django 5.2.17 on 2026-10-06 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashshift',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_shifts', to='pos.staffmember'),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='opened_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_shifts', to='pos.staffmember'),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts', to='pos.venue'),
        ),
        migrations.AddConstraint(
            model_name='cashshift',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('venue',), name='one_open_shift_per_venue'),
        ),
    ]
