# Generated by Django 5.2.17 on 2026-10-08 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("house_account", "0001_initial"),
        ("ordering", "0002_order_idempotency"),
    ]

    operations = [
        migrations.AddField(
            model_name="tab",
            name="action_reasons",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="tab",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tabs",
                to="house_account.customer",
            ),
        ),
        migrations.AddField(
            model_name="tab",
            name="operating_limit_cents",
            field=models.PositiveIntegerField(default=3000),
        ),
        migrations.AddField(
            model_name="tab",
            name="policy_version_snapshot",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="tab",
            name="relationship_snapshot",
            field=models.CharField(default="VISITOR", max_length=16),
        ),
    ]
