# Generated by Django 5.2.17 on 2026-10-08 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_tab_action_reasons_tab_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='tab',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_sources', to='ordering.tab'),
        ),
    ]
