# Generated by Django 5.2.17 on 2026-10-08 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0004_tab_cancel_reason_tab_merged_into'),
        ('tab_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='service_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tab_operations.servicepoint'),
        ),
    ]
