# Generated by Django 5.2.17 on 2026-10-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_tab_service_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customization_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_station_snapshot',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
