# Generated by Django 5.2.17 on 2026-10-08 18:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0002_tab_assignment_allows_guest_actor'),
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitality_zones', to='venue.venue')),
            ],
            options={
                'ordering': ('label', 'id'),
            },
        ),
        migrations.AddField(
            model_name='table',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='hospitality.zone'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['venue', 'is_active'], name='hospitality_zone_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('venue', 'label'), name='hospitality_zone_venue_label_uniq'),
        ),
    ]
