# Generated by Django 5.2.17 on 2026-10-09 17:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_access_invalidation_event'),
        ('guest_access', '0001_initial'),
        ('hospitality', '0003_zone_context'),
        ('ordering', '0006_orderitem_customization_snapshot_and_more'),
        ('venue', '0002_venue_business_day_cutoff_hour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartySizeObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('covers_count', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('STAFF', 'Staff'), ('GUEST', 'Guest'), ('IMPORTED', 'Imported')], max_length=8)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('observed_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('guest_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='guest_access.guestsession')),
                ('occupancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='party_size_observations', to='hospitality.tableoccupancy')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='access.staffmember')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='hospitality.partysizeobservation')),
                ('tab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='party_size_observations', to='ordering.tab')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venue.venue')),
            ],
            options={
                'ordering': ('-version',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('occupancy__isnull', False), ('tab__isnull', True)), models.Q(('occupancy__isnull', True), ('tab__isnull', False)), _connector='OR'), name='party_size_one_target'), models.CheckConstraint(condition=models.Q(('covers_count__gt', 0)), name='party_size_positive_count'), models.UniqueConstraint(fields=('occupancy', 'version'), name='party_size_occ_version'), models.UniqueConstraint(fields=('tab', 'version'), name='party_size_tab_version'), models.UniqueConstraint(fields=('venue', 'idempotency_key'), name='party_size_request_unique')],
            },
        ),
    ]
