# Generated by Django 5.2.17 on 2026-10-08 22:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0003_access_invalidation_event'),
        ('ledger', '0006_remove_ledgeradjustment_ledger_adjustment_cancellation_negative_and_more'),
        ('ordering', '0004_tab_cancel_reason_tab_merged_into'),
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=24)),
                ('response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.staffmember')),
                ('source_tab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='ordering.tab')),
            ],
        ),
        migrations.CreateModel(
            name='TabTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('SPLIT', 'SPLIT'), ('MOVE_ITEMS', 'MOVE_ITEMS'), ('MERGE', 'MERGE')], max_length=16)),
                ('status', models.CharField(choices=[('COMMITTED', 'COMMITTED')], default='COMMITTED', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('source_version', models.PositiveIntegerField()),
                ('destination_version', models.PositiveIntegerField()),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
                ('destination_tab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='ordering.tab')),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer', to='tab_operations.taboperation')),
                ('source_tab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='ordering.tab')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venue.venue')),
            ],
        ),
        migrations.CreateModel(
            name='TabTransferLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('source_charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='ledger.charge')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='tab_operations.tabtransfer')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venue.venue')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('venue', 'label'), name='tabop_point_label_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='taboperation',
            constraint=models.UniqueConstraint(fields=('source_tab', 'idempotency_key'), name='tabop_command_key_unique'),
        ),
        migrations.AddIndex(
            model_name='tabtransfer',
            index=models.Index(fields=['venue', 'committed_at'], name='tabop_venue_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='tabtransfer',
            constraint=models.CheckConstraint(condition=models.Q(('source_tab', models.F('destination_tab')), _negated=True), name='tabop_distinct_tabs'),
        ),
        migrations.AddConstraint(
            model_name='tabtransferline',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='tabop_line_positive'),
        ),
        migrations.AddConstraint(
            model_name='tabtransferline',
            constraint=models.UniqueConstraint(fields=('transfer', 'source_charge'), name='tabop_transfer_charge_unique'),
        ),
    ]
