# Generated by Django 5.2.17 on 2026-10-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabtransferline',
            name='components',
            field=models.JSONField(default=dict),
        ),
    ]
