# Generated by Django 5.2.18 on 2026-10-08 22:25

import django.db.models.deletion
from django.db import migrations, models


def seed_icons(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    Icon = apps.get_model("catalog", "ProductIcon")
    Icon.objects.using(schema_editor.connection.alias).bulk_create(
        [Icon(product_id=product_id) for product_id in Product.objects.using(schema_editor.connection.alias).values_list("id", flat=True)],
        batch_size=1000,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIcon',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='icon', serialize=False, to='catalog.product')),
                ('source', models.CharField(default='NONE', max_length=24)),
                ('status', models.CharField(default='FAILED', max_length=16)),
                ('published_asset_url', models.URLField(blank=True)),
                ('style_version', models.CharField(default='rodada-icon-v1', max_length=40)),
                ('error_code', models.CharField(default='GENERATOR_NOT_CONFIGURED', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(seed_icons, migrations.RunPython.noop),
    ]
