# Generated by Django 5.2.17 on 2026-10-08 22:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_access_invalidation_event'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.CreateModel(
            name='ProductIcon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('NONE', 'NONE'), ('AI_GENERATED', 'AI_GENERATED'), ('UPLOADED', 'UPLOADED')], default='NONE', max_length=16)),
                ('status', models.CharField(choices=[('NONE', 'NONE'), ('GENERATING', 'GENERATING'), ('READY', 'READY'), ('FAILED', 'FAILED')], default='NONE', max_length=16)),
                ('published_asset', models.CharField(blank=True, max_length=240)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='icon', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='IconGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64)),
                ('request_key', models.CharField(max_length=100)),
                ('revision', models.PositiveIntegerField()),
                ('context', models.JSONField()),
                ('prompt', models.TextField()),
                ('style_version', models.CharField(max_length=40)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('usage', models.JSONField(default=dict)),
                ('asset', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField()),
                ('lease_until', models.DateTimeField(null=True)),
                ('claim_token', models.UUIDField(null=True)),
                ('error', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='access.staffmember')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='catalog.producticon')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'available_at'], name='catalog_icon_jobs_idx')],
                'constraints': [models.UniqueConstraint(fields=('icon', 'request_key'), name='catalog_icon_request_unique')],
            },
        ),
    ]
