# Generated by Django 5.2.17 on 2026-10-08 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_product_category_product_description_producticon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="icongeneration",
            name="request_key",
            field=models.CharField(max_length=160),
        ),
        migrations.CreateModel(
            name="IconGenerationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=160)),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.icongeneration"
                    ),
                ),
                (
                    "icon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.producticon"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("icon", "key"), name="catalog_icon_alias_unique"
                    )
                ],
            },
        ),
    ]
