# Generated by Django 5.2.18 on 2026-10-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_backfill_catalog_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icongeneration',
            name='error',
            field=models.CharField(blank=True, db_default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='icongeneration',
            name='model',
            field=models.CharField(blank=True, db_default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='icongeneration',
            name='provider',
            field=models.CharField(blank=True, db_default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, db_default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, db_default='', max_length=600),
        ),
    ]
