# Generated by Django 5.2.17 on 2026-10-09 02:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_normalize_existing_names'),
        ('venue', '0002_venue_business_day_cutoff_hour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('selection_mode', models.CharField(choices=[('SINGLE', 'Single'), ('MULTI', 'Multi')], max_length=8)),
                ('min_selections', models.PositiveIntegerField(default=0)),
                ('max_selections', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modifier_groups', to='venue.venue')),
            ],
        ),
        migrations.CreateModel(
            name='ModifierOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price_delta_cents', models.PositiveIntegerField(default=0)),
                ('semantic_kind', models.CharField(choices=[('ADD', 'Add'), ('REMOVE', 'Remove'), ('CHOICE', 'Choice')], default='CHOICE', max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('default_selected', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.modifiergroup')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='catalog.modifiergroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_links', to='catalog.product')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price_cents', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='modifiergroup',
            constraint=models.CheckConstraint(condition=models.Q(('max_selections__gte', models.F('min_selections')), ('max_selections__gte', 1)), name='catalog_group_bounds'),
        ),
        migrations.AddConstraint(
            model_name='modifiergroup',
            constraint=models.CheckConstraint(condition=models.Q(('selection_mode', 'MULTI'), models.Q(('max_selections', 1), ('selection_mode', 'SINGLE')), _connector='OR'), name='catalog_single_group_max'),
        ),
        migrations.AddConstraint(
            model_name='productmodifiergroup',
            constraint=models.UniqueConstraint(fields=('product', 'group'), name='catalog_product_group_unique'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('is_default', True)), fields=('product',), name='catalog_one_default_variant'),
        ),
    ]
