import { expect, test, type Page } from "@playwright/test";
import path from "node:path";
import { mkdir } from "node:fs/promises";
async function api(page: Page, route: string, data?: object) {
  const result = await page.evaluate(async ({ route, data }) => {
    const response = await fetch(`/api/pos/${route}`, { method: data ? "POST" : "GET", headers: { "Content-Type": "application/json" }, ...(data ? { body: JSON.stringify(data) } : {}) });
    return { status: response.status, body: await response.json() };
  }, { route, data });
  expect(result.status, JSON.stringify(result.body)).toBeLessThan(300);
  return result.body;
}

test("canonical order, station ticket, partial receipt, final bill and audited copy", async ({ page, context }) => {
  await page.goto("/staff");
  await page.getByLabel("Estabelecimento").fill("web-e2e");
  await page.getByLabel("Operador", { exact: true }).fill("test-manager");
  await page.getByLabel("PIN", { exact: true }).fill("2468");
  await page.getByRole("button", { name: "Entrar", exact: true }).click();
  await expect(page.getByText("Sessão operacional ativa")).toBeVisible();
  await page.goto("/manage/printing");
  await page.getByLabel("Nome", { exact: true }).fill("Printing browser E2E");
  await page.getByRole("button", { name: "Bar", exact: true }).click();
  await page.getByRole("button", { name: "Cozinha", exact: true }).click();
  await page.getByRole("button", { name: "Salvar destino" }).click();
  await expect(page.getByText("Printing browser E2E", { exact: true })).toBeVisible();
  const endpoint = (await api(page, "printing/endpoints/")).results.find((e: { label: string }) => e.label === "Printing browser E2E");
  const products = (await api(page, "catalog/products/")).results.filter((p: { name: string }) => ["Kitchen E2E item", "Bar E2E item"].includes(p.name));
  const tab = await api(page, "tabs/", { display_label: "Printing E2E tab" });
  const order = await api(page, `tabs/${tab.id}/orders/confirm/`, { idempotency_key: "printing-e2e-order", lines: products.map((p: { id: string }) => ({ product_id: p.id, quantity: 1 })) });
  await page.goto("/bar");
  const ticket = page.locator(".stationTools .dataRow").filter({ hasText: "Printing E2E tab" });
  await ticket.getByRole("button", { name: "Ver / imprimir ticket" }).click();
  await ticket.getByLabel("Destino").selectOption(endpoint.id);
  await expect(ticket.frameLocator("iframe").locator("pre")).toContainText("Bar E2E item");
  await expect(ticket.frameLocator("iframe").locator("pre")).not.toContainText("Kitchen E2E item");
  await ticket.getByRole("button", { name: "Imprimir", exact: true }).click();
  await expect(ticket.getByRole("status")).toContainText("Documento disponível");
  // Simulated operator audit input; no physical printer was used.
  await ticket.getByRole("button", { name: "Confirmar que vi o papel" }).click();
  await expect(ticket.getByRole("status")).toContainText("Papel confirmado pelo operador");
  await ticket.getByLabel("Motivo da cópia").fill("Teste de cópia explícita");
  await ticket.getByRole("button", { name: "Reimprimir cópia" }).click();
  await expect(ticket.frameLocator("iframe").locator("pre")).toContainText("REIMPRESSÃO");
  const jobs = await api(page, "printing/jobs/");
  expect(jobs.results.filter((j: { reprint_of: string | null }) => j.reprint_of).length).toBeGreaterThan(0);
  await api(page, `tabs/${tab.id}/payments/`, { amount_cents: 500, method: "EXTERNAL_TERMINAL", idempotency_key: "printing-e2e-partial" });
  await page.goto("/pos");
  await page.getByRole("button", { name: /Printing E2E tab/ }).click();
  await page.getByRole("button", { name: "Ver conta / recibos" }).click();
  const preview = page.frameLocator("iframe[title='Documento não fiscal']");
  await expect(preview.locator("pre")).toContainText("Saldo: R$ 10,00");
  const detail = await api(page, `tabs/${tab.id}/`);
  await page.getByLabel("Pagamento confirmado").selectOption(detail.payments[0].id);
  await page.getByRole("button", { name: "Ver recibo do pagamento" }).click();
  await expect(preview.locator("pre")).toContainText("RECIBO DE PAGAMENTO PARCIAL");
  await page.getByRole("button", { name: "Criar link do recibo (24 horas)" }).click();
  const link = await page.getByLabel("Link de leitura").inputValue();
  const shared = await context.newPage();
  await shared.goto(link);
  await expect(shared.locator("pre")).toContainText("RECIBO DE PAGAMENTO PARCIAL");
  await page.getByRole("button", { name: "Revogar link" }).click();
  await shared.reload();
  await expect(shared.locator("p[role=alert]")).toContainText("expirou");
  await shared.close();
  await api(page, `tabs/${tab.id}/payments/`, { amount_cents: 1000, method: "EXTERNAL_TERMINAL", idempotency_key: "printing-e2e-final" });
  await api(page, `tabs/${tab.id}/close/`, {});
  await page.reload();
  await page.getByRole("button", { name: /Printing E2E tab/ }).click();
  await page.getByRole("button", { name: "Ver conta / recibos" }).click();
  await expect(preview.locator("pre")).toContainText("COMANDA ENCERRADA");
  await expect(preview.locator("pre")).toContainText("Saldo: R$ 0,00");
  await expect(page.getByRole("button", { name: "Receber em dinheiro", exact: true })).toHaveCount(0);
  const final = await api(page, "printing/documents/", { tab_id: tab.id, kind: "CLOSED_TAB_RECEIPT" });
  const output = await context.newPage();
  await output.setContent(final.html);
  await output.emulateMedia({ media: "print" });
  const directory = path.resolve(process.cwd(), "../../visual-artifacts/printing");
  await mkdir(directory, { recursive: true });
  const pdf = await output.pdf({ path: path.join(directory, "closed-tab-80mm.pdf"), width: "80mm", height: "250mm", printBackground: false });
  expect(pdf.subarray(0, 4).toString()).toBe("%PDF");
  expect(pdf.length).toBeGreaterThan(1000);
  await output.close();
  await page.screenshot({ path: path.join(directory, "cashier-receipt-390.png"), fullPage: true });
  expect(order.status).toBe("CONFIRMED");
});
