# Generated by Django 5.2.17 on 2026-10-08 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0001_initial'),
        ('ledger', '0005_correction_financial_reversal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercorrection',
            name='financial_adjustment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction', to='ledger.ledgeradjustment'),
        ),
    ]
