# Generated by Django 5.2.17 on 2026-10-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0003_refund_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercorrection',
            name='refund_required_cents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
