"use client";
import { useCallback, useEffect, useMemo, useState } from "react";

const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000/api";
const WS=process.env.NEXT_PUBLIC_WS_URL||API.replace(/^http/,"ws").replace(/\/api\/?$/,"");
const VENUE_ID=Number(process.env.NEXT_PUBLIC_VENUE_ID||1);
const money=(c=0)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(c/100);
const labels={NEW:"Novo",ACCEPTED:"Aceito",PREPARING:"Preparando",READY:"Pronto",PICKED_UP:"Retirado",DELIVERED:"Entregue",CANCELLED:"Cancelado"};
const next={NEW:["ACCEPTED","Aceitar"],ACCEPTED:["READY","Pronto"],PREPARING:["READY","Pronto"],READY:["PICKED_UP","Pegar"],PICKED_UP:["DELIVERED","Entregar"]};
async function api(path,options={}){const token=typeof window==="undefined"?"":localStorage.getItem("rodada-session-token");const response=await fetch(`${API}${path}`,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{}),...options.headers}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.detail||"Não foi possível concluir.");return payload}
const age=i=>{const start=i.ready_at||i.preparing_at||i.accepted_at||i.created_at;return start?Math.max(0,Math.floor((Date.now()-new Date(start).getTime())/1000)):0};
const elapsed=s=>`${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`;
const urgency=(s,state)=>state==="READY"&&s>=180||s>=720?"danger":s>=480?"hot":s>=180?"warm":"calm";

export default function Pos(){
 const [staff,setStaff]=useState(null);
 const [view,setView]=useState("now"),[tabs,setTabs]=useState([]),[products,setProducts]=useState([]),[points,setPoints]=useState([]),[shifts,setShifts]=useState([]),[tasks,setTasks]=useState([]),[customers,setCustomers]=useState([]),[physicalTables,setPhysicalTables]=useState([]);
 const [selected,setSelected]=useState(null),[cart,setCart]=useState({}),[query,setQuery]=useState("");
 const [opening,setOpening]=useState(false),[newLabel,setNewLabel]=useState(""),[newPoint,setNewPoint]=useState(""),[newCustomer,setNewCustomer]=useState("");
 const [paying,setPaying]=useState(false),[payMethod,setPayMethod]=useState("PIX"),[payValue,setPayValue]=useState("");
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState(null),[online,setOnline]=useState(true),[peak,setPeak]=useState(false),[clock,setClock]=useState(new Date());
 const [realtime,setRealtime]=useState("connecting");
 const [pending,setPending]=useState(()=>typeof window==="undefined"?[]:JSON.parse(localStorage.getItem("rodada-pending")||"[]"));
 const load=useCallback(async id=>{const [ts,ps,sps,css,dts,cts,pts]=await Promise.all([api("/tabs/"),api("/products/"),api("/service-points/"),api("/cash-shifts/"),api("/dispatch/tasks/"),api("/customers/"),api("/physical-tables/")]);setTabs(ts);setProducts(ps);setPoints(sps);setShifts(css);setTasks(dts);setCustomers(cts);setPhysicalTables(pts);if(id)setSelected(await api(`/tabs/${id}/`))},[]);
 useEffect(()=>{const token=localStorage.getItem("rodada-session-token");if(!token)return;api("/auth/session/").then(data=>setStaff(data.staff)).catch(()=>localStorage.removeItem("rodada-session-token"))},[]);
 useEffect(()=>{if(!staff)return;load().catch(e=>setNotice({type:"error",text:e.message}))},[load,staff]);
 useEffect(()=>{if(!staff)return;let socket,retry,stopped=false;const connect=()=>{setRealtime("connecting");const token=encodeURIComponent(localStorage.getItem("rodada-session-token")||"");socket=new WebSocket(`${WS}/ws/venues/${VENUE_ID}/dispatch/?session_token=${token}`);socket.onopen=()=>{setRealtime("connected");load(selected?.id).catch(()=>{})};socket.onmessage=()=>load(selected?.id).catch(()=>{});socket.onclose=()=>{if(!stopped){setRealtime("reconnecting");retry=setTimeout(connect,2000)}};socket.onerror=()=>socket.close()};connect();return()=>{stopped=true;clearTimeout(retry);socket?.close()}},[load,selected?.id,staff]);
 useEffect(()=>{localStorage.setItem("rodada-pending",JSON.stringify(pending))},[pending]);
 const syncPending=useCallback(async()=>{const queued=JSON.parse(localStorage.getItem("rodada-pending")||"[]");if(!queued.length){await load(selected?.id);return}const failed=[];for(const command of queued){try{if(command.kind==="order"){const created=await api(`/tabs/${command.tabId}/orders/`,{method:"POST",body:JSON.stringify({items:command.items,idempotency_key:command.key})});await api(`/orders/${created.id}/confirm/`,{method:"POST",body:"{}"})}else{await api(`/tabs/${command.tabId}/payments/`,{method:"POST",body:JSON.stringify({amount_cents:command.amount,method:"CASH",idempotency_key:command.key})})}}catch{failed.push(command)}}setPending(failed);localStorage.setItem("rodada-pending",JSON.stringify(failed));await load(selected?.id);setNotice(failed.length?{type:"error",text:`${failed.length} ação(ões) não sincronizada(s). Tente novamente.`}:{type:"success",text:"Sincronizado. Tudo foi enviado."})},[load,selected?.id]);
 useEffect(()=>{setOnline(navigator.onLine);const on=()=>{setOnline(true);syncPending()},off=()=>setOnline(false),timer=setInterval(()=>setClock(new Date()),1000);window.addEventListener("online",on);window.addEventListener("offline",off);return()=>{clearInterval(timer);window.removeEventListener("online",on);window.removeEventListener("offline",off)}},[syncPending]);
 const run=async fn=>{if(!online){setNotice({type:"error",text:"Sem sinal. Aguarde a reconexão para confirmar."});return}setBusy(true);setNotice(null);try{await fn()}catch(e){setNotice({type:"error",text:e.message})}finally{setBusy(false)}};
 const items=useMemo(()=>tabs.flatMap(t=>t.orders.flatMap(o=>o.items.map(i=>({...i,tabLabel:t.label||`Comanda ${t.id}`,point:t.service_point_code||"Sem ponto",orderId:o.id,age:age(i)})))).filter(i=>!["DELIVERED","CANCELLED"].includes(i.state)).sort((a,b)=>b.age-a.age),[tabs,clock]);
 const visibleTabs=useMemo(()=>tabs.filter(t=>`${t.label} ${t.service_point_code||""} ${t.id}`.toLowerCase().includes(query.toLowerCase())),[tabs,query]);
 const rows=useMemo(()=>products.filter(p=>cart[p.id]).map(p=>({...p,quantity:cart[p.id]})),[cart,products]),total=rows.reduce((s,r)=>s+r.current_price_cents*r.quantity,0),shift=shifts.find(s=>!s.closed_at);
 const quantity=(id,d)=>setCart(c=>({...c,[id]:Math.max(0,(c[id]||0)+d)}));
 const selectTab=(id,dest="tab")=>run(async()=>{setSelected(await api(`/tabs/${id}/`));setCart({});setView(dest)});
 const openTab=()=>run(async()=>{const tab=await api("/tabs/",{method:"POST",body:JSON.stringify({venue_id:1,label:newLabel.trim(),customer_id:newCustomer||null,service_point_id:newPoint||null})});setOpening(false);setNewLabel("");setNewPoint("");setNewCustomer("");setSelected(tab);setCart({});setView("order");await load(tab.id);setNotice({type:"success",text:"Comanda aberta. Pode pedir."})});
 const order=()=>{const items=rows.map(r=>({product_id:r.id,quantity:r.quantity})),key=crypto.randomUUID();if(!online){setPending(q=>[...q,{kind:"order",tabId:selected.id,items,key}]);setCart({});setNotice({type:"success",text:"Pedido na fila. Vai sozinho quando o sinal voltar."});return}run(async()=>{const created=await api(`/tabs/${selected.id}/orders/`,{method:"POST",body:JSON.stringify({items,idempotency_key:key})});await api(`/orders/${created.id}/confirm/`,{method:"POST",body:"{}"});setCart({});await load(selected.id);setNotice({type:"success",text:"Pedido enviado para Bar e Cozinha."})})};
 const advance=item=>run(async()=>{await api(`/order-items/${item.id}/transition/`,{method:"POST",body:JSON.stringify({state:next[item.state][0]})});await load(selected?.id)});
 const dispatch=task=>run(async()=>{await api(`/dispatch/tasks/${task.id}/${task.state==="OPEN"?"claim":"done"}/`,{method:"POST",body:"{}"});await load(selected?.id)});
 const move=id=>run(async()=>{await api(`/tabs/${selected.id}/service-point/`,{method:"POST",body:JSON.stringify({service_point_id:id||null})});await load(selected.id);setNotice({type:"success",text:"Lugar atualizado. A conta não mudou."})});
 const receive=()=>{const amount=Math.round(Number(payValue.replace(",","."))*100),key=crypto.randomUUID();if(!Number.isFinite(amount)||amount<=0){setNotice({type:"error",text:"Informe um valor válido."});return}if(amount>selected.exposure_cents){setNotice({type:"error",text:"O valor é maior que o saldo."});return}if(!online){if(payMethod!=="CASH"){setNotice({type:"error",text:"Pix e cartão precisam de sinal. Use dinheiro ou aguarde."});return}setPending(q=>[...q,{kind:"payment",tabId:selected.id,amount,key}]);setPaying(false);setPayValue("");setNotice({type:"success",text:"Dinheiro na fila. Confirma ao sincronizar."});return}run(async()=>{await api(`/tabs/${selected.id}/payments/`,{method:"POST",body:JSON.stringify({amount_cents:amount,method:payMethod,idempotency_key:key})});setPaying(false);setPayValue("");await load(selected.id);setNotice({type:"success",text:`${money(amount)} recebido.`})})};
 const close=()=>run(async()=>{await api(`/tabs/${selected.id}/close/`,{method:"POST",body:"{}"});setSelected(null);setView("accounts");await load();setNotice({type:"success",text:"Comanda fechada."})});
 const setTableStatus=(table,status)=>run(async()=>{await api(`/physical-tables/${table.id}/lifecycle/`,{method:"POST",body:JSON.stringify({status})});await load(selected?.id)});
 const tapToPay=()=>{const amount=Math.round(Number(payValue.replace(",","."))*100);if(!Number.isFinite(amount)||amount<=0||amount>selected.exposure_cents){setNotice({type:"error",text:"Informe um valor dentro do saldo."});return}run(async()=>{const intent=await api(`/tabs/${selected.id}/payment-intents/`,{method:"POST",body:JSON.stringify({amount_cents:amount,method:"CARD",idempotency_key:crypto.randomUUID()})});if(!intent.test_mode)throw new Error("O provedor exige um terminal/dispositivo configurado.");await api(`/payment-intents/${intent.id}/test-confirm/`,{method:"POST",body:"{}"});setPaying(false);await load(selected.id);setNotice({type:"success",text:"Pagamento TEST confirmado no dispositivo."})})};
 const startOrder=()=>selected?setView("order"):setView("accounts");
 if(!staff)return <StaffLogin onSuccess={setStaff}/>;
 return <div className={`app ${peak?"peak":""}`}><header className="topbar"><button className="brand" onClick={()=>setView("now")}><i/>rodada</button><div className="staff"><span>{online?(realtime==="connected"?staff.display_name:"Reconectando…"):"Sem sinal"}</span><b>{staff.display_name.slice(0,2).toUpperCase()}</b></div></header>
 {!online&&<div className="network"><Icon name="offline"/><b>Sem sinal</b><span>{pending.length} ação(ões) aguardando envio</span></div>}{online&&pending.length>0&&<button className="network sync" onClick={syncPending}>Sincronizar {pending.length} ação(ões)</button>}{notice&&<div className={`toast ${notice.type}`} role="status"><b>{notice.type==="success"?"✓":"!"}</b><span>{notice.text}</span><button onClick={()=>setNotice(null)}>×</button></div>}
 <main>{view==="now"&&<Now tasks={tasks} peak={peak} setPeak={setPeak} clock={clock} busy={busy} dispatch={dispatch}/>} {view==="accounts"&&<Accounts tabs={visibleTabs} all={tabs} query={query} setQuery={setQuery} open={()=>setOpening(true)} select={selectTab} map={()=>setView("tables")}/>} {view==="tables"&&<TableMap tables={physicalTables} busy={busy} setStatus={setTableStatus} back={()=>setView("accounts")}/>} {view==="tab"&&selected&&<Tab tab={selected} points={points} busy={busy} move={move} back={()=>setView("accounts")} order={()=>setView("order")} pay={()=>{setPayValue((selected.exposure_cents/100).toFixed(2).replace(".",","));setPaying(true)}} close={close}/>} {view==="order"&&<Order selected={selected} tabs={tabs} products={products} cart={cart} rows={rows} total={total} busy={busy} quantity={quantity} target={id=>selectTab(Number(id),"order")} submit={order}/>} {view==="kitchen"&&<Kitchen items={items.filter(i=>i.fulfillment_station==="KITCHEN")} busy={busy} advance={advance} clock={clock}/>} {view==="cash"&&<Cash shift={shift}/>}</main>
 <nav className="nav"><Nav active={view==="now"} icon="clock" label="Agora" badge={items.length} onClick={()=>setView("now")}/><button className="order-cta" onClick={startOrder}>+ Pedir</button><Nav active={["accounts","tab"].includes(view)} icon="people" label="Contas" onClick={()=>setView("accounts")}/><Nav active={view==="kitchen"} icon="fire" label="Cozinha" onClick={()=>setView("kitchen")}/><Nav active={view==="cash"} icon="cash" label="Caixa" onClick={()=>setView("cash")}/></nav>
 {opening&&<Modal close={()=>setOpening(false)} title="Abrir comanda" eyebrow="NOVO ATENDIMENTO"><label><span>Cliente conhecido <small>opcional</small></span><select value={newCustomer} onChange={e=>setNewCustomer(e.target.value)}><option value="">Visitante / sem cadastro</option>{customers.map(c=><option key={c.id} value={c.id}>{c.nickname||c.display_name} · {c.relationship}</option>)}</select></label><label><span>Nome ou identificação <small>opcional</small></span><input autoFocus value={newLabel} onChange={e=>setNewLabel(e.target.value)} placeholder="Ex.: João da Oficina"/></label><label><span>Onde está? <small>pode definir depois</small></span><select value={newPoint} onChange={e=>setNewPoint(e.target.value)}><option value="">Sem localização</option>{points.map(p=><option key={p.id} value={p.id}>{p.code} · {p.zone}</option>)}</select></label><button className="btn primary full" disabled={busy||!online} onClick={openTab}>Abrir comanda</button></Modal>}
 {paying&&<Modal close={()=>setPaying(false)} title="Receber" eyebrow="PAGAMENTO"><div className="payment-balance"><span>Em aberto</span><strong>{money(selected?.exposure_cents)}</strong></div><label><span>Valor recebido</span><div className="money-input"><b>R$</b><input inputMode="decimal" value={payValue} onChange={e=>setPayValue(e.target.value)}/></div></label><div className="method-picker">{[["PIX","Pix"],["CARD","Cartão"],["CASH","Dinheiro"],["OTHER","Outro"]].map(([id,label])=><button className={payMethod===id?"active":""} disabled={!online&&id!=="CASH"} key={id} onClick={()=>setPayMethod(id)}>{label}</button>)}</div>{payMethod==="CARD"?<button className="btn violet full" disabled={busy||!online} onClick={tapToPay}>Aproximar cartão · teste</button>:<button className="btn primary full" disabled={busy} onClick={receive}>Confirmar recebimento</button>}{!online&&<p className="offline-help">Dinheiro fica guardado no aparelho. Pix e cartão aguardam sinal.</p>}</Modal>}</div>
}

function StaffLogin({onSuccess}){const [name,setName]=useState("Ana Gerente"),[pin,setPin]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const login=async e=>{e.preventDefault();setBusy(true);setError("");try{const response=await fetch(`${API}/auth/login/`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({venue_id:VENUE_ID,display_name:name,pin})});const data=await response.json();if(!response.ok)throw new Error(data.detail||"Não foi possível entrar.");localStorage.setItem("rodada-session-token",data.session_token);onSuccess(data.staff)}catch(err){setError(err.message)}finally{setBusy(false)}};return <main className="login-page"><form className="login-card" onSubmit={login}><span className="kicker">RODADA ATENDIMENTO</span><h1>Entrar no turno</h1><p>Use sua identificação e PIN para operar o bar.</p><label>Nome<input value={name} onChange={e=>setName(e.target.value)} autoFocus required/></label><label>PIN<input value={pin} onChange={e=>setPin(e.target.value)} inputMode="numeric" type="password" required/></label>{error&&<p className="login-error" role="alert">{error}</p>}<button className="btn primary full" disabled={busy}>{busy?"Entrando…":"Entrar"}</button></form></main>}
function Now({tasks,peak,setPeak,clock,busy,dispatch}){const queue=peak?tasks.filter(t=>["HIGH","CRITICAL"].includes(t.severity)||t.type==="DELIVERY"):tasks,claimed=tasks.filter(t=>t.state==="CLAIMED").length,late=tasks.filter(t=>t.severity==="CRITICAL").length;return <section><div className="screen-head"><div><span className="kicker">{peak?"MODO PICO · SÓ O ESSENCIAL":"FILA OPERACIONAL"}</span><h1>Agora</h1></div><div className="head-tools"><time>{clock.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</time><button className={`toggle ${peak?"on":""}`} onClick={()=>setPeak(!peak)}><Icon name="bolt"/>Pico <i/></button></div></div><div className="counters"><div className="green"><b>{claimed}</b><span>Em curso</span></div><div className="red"><b>{late}</b><span>Atrasadas</span></div><div className="violet"><b>{tasks.length}</b><span>Na fila</span></div></div><div className="queue-label"><span>Prioridade e idade</span><span>{queue.length} ações</span></div><div className="queue">{queue.map(t=><DispatchRow task={t} key={t.id} busy={busy} dispatch={dispatch}/>)}{!queue.length&&<Empty title="Tudo em dia">Nenhuma ação esperando agora.</Empty>}</div></section>}
function DispatchRow({task,busy,dispatch}){const type={DELIVERY:"Entrega",SERVICE_REQUEST:"Atendimento",BILL_REQUEST:"Conta",EXCEPTION:"Exceção"}[task.type];const tone={CRITICAL:"danger",HIGH:"hot",MEDIUM:"warm",NORMAL:"calm"}[task.severity];return <article className={`queue-row ${tone}`}><div className="age"><span>{type}</span><b>{elapsed(task.age_seconds)}</b></div><div className="queue-body"><h2>{task.service_point||"Sem ponto"} <small>{task.zone||"Sem zona"}</small></h2><p>{task.note||type}</p><small>{task.claimed_by?`Responsável: ${task.claimed_by}`:"Sem responsável"}</small></div><button className="btn action" disabled={busy} onClick={()=>dispatch(task)}>{task.state==="OPEN"?"Assumir":"Concluir"}</button></article>}
function Queue({item,busy,advance}){const action=next[item.state];return <article className={`queue-row ${urgency(item.age,item.state)}`}><div className="age"><span>{labels[item.state]}</span><b>{elapsed(item.age)}</b></div><div className="queue-body"><h2>{item.point} <small>{item.fulfillment_station==="KITCHEN"?"Cozinha":"Bar"}</small></h2><p>{item.quantity}× {item.product_name}</p><small>{item.tabLabel} · Pedido #{item.orderId}</small></div>{action&&<button className="btn action" disabled={busy} onClick={()=>advance(item)}>{action[1]}</button>}</article>}
function Accounts({tabs,all,query,setQuery,open,select,map}){return <section><div className="screen-head"><div><span className="kicker">CONTAS ABERTAS</span><h1>Contas</h1><p>{all.length} em atendimento · {money(all.reduce((s,t)=>s+t.exposure_cents,0))} em aberto</p></div><div className="head-tools"><button className="btn secondary" onClick={map}>Mapa</button><button className="btn primary" onClick={open}>+ Nova</button></div></div><label className="search"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome, número ou ponto"/></label><div className="account-list">{tabs.map(t=><button key={t.id} onClick={()=>select(t.id)}><span className="avatar">{(t.label||String(t.id)).slice(0,2).toUpperCase()}</span><span><b>{t.label||`Comanda #${t.id}`}</b><small>{t.service_point_code||"Sem localização"}</small></span><strong>{money(t.exposure_cents)}<small>em aberto</small></strong><em>›</em></button>)}</div>{!tabs.length&&<Empty title="Ninguém encontrado">Ajuste a busca ou abra uma comanda.</Empty>}</section>}
function TableMap({tables,busy,setStatus,back}){return <section><div className="screen-head"><div><button className="link" onClick={back}>← Contas</button><span className="kicker">AMBIENTE FLEXÍVEL</span><h1>Mapa</h1><p>Mesas são contexto físico, não a conta.</p></div></div><div className="table-map">{tables.map(t=><article key={t.id} className={`table-node ${t.status.toLowerCase()}`} style={{left:`${t.x}%`,top:`${t.y}%`}}><b>{t.label}</b><small>{t.zone||"Sem área"}{t.temporary?" · temporária":""}</small><span>{t.status==="AVAILABLE"?"Livre":t.status==="OCCUPIED"?"Em uso":"Limpar"}</span><div>{t.status==="OCCUPIED"?<button disabled={busy} onClick={()=>setStatus(t,"NEEDS_CLEANING")}>Liberar</button>:<button disabled={busy} onClick={()=>setStatus(t,"AVAILABLE")}>{t.status==="NEEDS_CLEANING"?"Concluir limpeza":"Disponível"}</button>}</div></article>)}</div><p className="offline-help">A ocupação é derivada quando uma comanda é associada. Só a transição de limpeza exige toque.</p></section>}
function Tab({tab,points,busy,move,back,order,pay,close}){const its=tab.orders.flatMap(o=>o.items);return <section><div className="tab-heading"><button className="link" onClick={back}>← Contas</button><span className="kicker">COMANDA #{tab.id}{tab.relationship?` · ${tab.relationship}`:""}</span><h1>{tab.customer_name||tab.label||"Sem nome"}</h1><label className="location"><Icon name="pin"/><select value={tab.service_point||""} onChange={e=>move(e.target.value)} disabled={busy}><option value="">Sem ponto</option>{points.map(p=><option key={p.id} value={p.id}>{p.code} · {p.zone}</option>)}</select></label></div><div className="exposure"><span>Em aberto</span><strong>{money(tab.exposure_cents)}</strong><small>Limite {money(tab.operating_limit_cents)} · {tab.payments.length?`${tab.payments.length} pagamento(s)`:"sem pagamentos"}</small></div><div className="section-title">Consumo</div><div className="consumption">{its.map(i=><div key={i.id}><b>{i.quantity}</b><span>{i.product_name}</span><em className={`state ${i.state.toLowerCase()}`}>{labels[i.state]}</em><strong>{money((i.unit_price_cents||0)*i.quantity)}</strong></div>)}{!its.length&&<Empty title="Comanda vazia">Faça o primeiro pedido.</Empty>}</div><div className="tab-actions"><button className="btn primary" onClick={order}>+ Pedir</button><button className="btn violet" onClick={pay} disabled={tab.exposure_cents<=0}>Receber</button><button className="btn secondary" disabled={tab.exposure_cents!==0||busy} onClick={close}>Fechar</button></div></section>}
function Order({selected,tabs,products,cart,rows,total,busy,quantity,target,submit}){return <section><div className="order-target"><div><span className="kicker">PEDIDO PARA</span><select value={selected?.id||""} onChange={e=>target(e.target.value)}><option value="">Escolha uma conta</option>{tabs.map(t=><option key={t.id} value={t.id}>{t.service_point_code?`${t.service_point_code} · `:""}{t.label||`Comanda ${t.id}`}</option>)}</select></div>{selected&&<b>{money(selected.exposure_cents)}<small>em aberto</small></b>}</div>{selected?<>{["KITCHEN","BAR"].map(g=><div key={g}><div className="product-label"><span><Icon name={g==="KITCHEN"?"fire":"cup"}/>{g==="KITCHEN"?"Cozinha":"Bar"}</span><span>Cada toque = +1</span></div><div className="product-grid">{products.filter(p=>p.fulfillment_station===g).map(p=><button className={`${cart[p.id]?"chosen":""} ${!p.available?"unavailable":""}`} key={p.id} disabled={!p.available||busy} onClick={()=>quantity(p.id,1)}><strong>{p.name}</strong><small>{!p.available?"Indisponível":money(p.current_price_cents)}</small>{cart[p.id]>0&&<em>{cart[p.id]}</em>}</button>)}</div></div>)}<div className="cart-dock"><div>{rows.length?rows.map(r=><span key={r.id}><b>{r.quantity}×</b> {r.name}<button onClick={()=>quantity(r.id,-1)}>−</button></span>):<small>Toque nos produtos para montar o pedido</small>}</div><strong>{money(total)}</strong><button className="btn primary" disabled={!rows.length||busy} onClick={submit}>Enviar</button></div></>:<Empty title="Para quem é o pedido?">Escolha uma conta aberta acima.</Empty>}</section>}
function Kitchen({items,busy,advance,clock}){const active=items.filter(i=>["NEW","ACCEPTED","PREPARING"].includes(i.state)),pass=items.filter(i=>i.state==="READY"),totals=active.reduce((r,i)=>({...r,[i.product_name]:(r[i.product_name]||0)+i.quantity}),{});return <section className="kitchen-view"><header><div><Icon name="fire"/><h1>Cozinha</h1><span>chapa · fritadeira · meta 12 min</span></div><aside><b>{active.length}</b> pedidos <b className="red-text">{active.filter(i=>i.age>720).length}</b> passou da meta <time>{clock.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</time></aside></header><div className="kitchen-board"><div className="dish-column"><div className="column-label">Fazer agora · por prato</div>{Object.entries(totals).map(([name,count])=><div className="dish" key={name}><span><b>{name}</b><small>{active.filter(i=>i.product_name===name).map(i=>i.point).join(" · ")}</small></span><strong>{count}</strong></div>)}</div><div className="ticket-column"><div className="column-label">Por pedido · mais antigo primeiro</div>{active.map(i=><div className="ticket" key={i.id}><b>{i.point}<small>{i.tabLabel}</small></b><span><strong>{i.quantity}× {i.product_name}</strong><i><em style={{width:`${Math.min(100,i.age/7.2)}%`}}/></i><small>{elapsed(i.age)}</small></span><button className="btn action" disabled={busy} onClick={()=>advance(i)}>{next[i.state]?.[1]}</button></div>)}</div><div className="pass-column"><div className="column-label">No passe · esperando retirada</div>{pass.map(i=><div className="pass" key={i.id}><b>{i.point}</b><span>{i.quantity}× {i.product_name}<small>Esperando · {elapsed(i.age)}</small></span><button className="btn action" disabled={busy} onClick={()=>advance(i)}>Pegar</button></div>)}</div></div></section>}
function Cash({shift}){const total=shift?Object.values(shift.payments_by_method).reduce((s,v)=>s+v,0):0;return <section><div className="screen-head"><div><span className="kicker">FINANCEIRO</span><h1>Caixa</h1><p>Recebimentos confirmados neste turno</p></div><span className={`shift ${shift?"open":""}`}><i/>{shift?"Aberto":"Fechado"}</span></div>{shift?<div className="cash-board"><div><span>Total recebido</span><strong>{money(total)}</strong><small>Desde {new Date(shift.opened_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</small></div><section>{[["PIX","Pix"],["CARD","Cartão"],["CASH","Dinheiro"],["OTHER","Outros"]].map(([id,label])=><p key={id}><span>{label}</span><b>{money(shift.payments_by_method[id]||0)}</b></p>)}</section><footer><span>Ajustes</span><b>{money(shift.adjustments_cents)}</b></footer></div>:<Empty title="Caixa fechado">Abra um turno para registrar recebimentos.</Empty>}</section>}
function Nav({active,icon,label,badge,onClick}){return <button className={`nav-button ${active?"active":""}`} onClick={onClick}><Icon name={icon}/>{badge>0&&<em>{badge}</em>}<span>{label}</span></button>}
function Empty({title,children}){return <div className="empty"><i>○</i><strong>{title}</strong><p>{children}</p></div>}
function Modal({close,eyebrow,title,children}){return <div className="modal-backdrop" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><header><div><span className="kicker">{eyebrow}</span><h2>{title}</h2></div><button onClick={close}>×</button></header>{children}</div></div>}
function Icon({name}){const p={clock:<><circle cx="12" cy="13" r="8"/><path d="M12 9v4l3 2"/></>,people:<><circle cx="9" cy="8" r="3.5"/><path d="M2.5 20a6.5 6.5 0 0113 0M16 5a3.5 3.5 0 010 7M18 15a6 6 0 013 5"/></>,fire:<path d="M12 22c4 0 7-2.7 7-6.5 0-4-3-6-4-9.5-2 1.5-3 3.5-3 5.5-1.5-1-2.5-2.5-2.5-4C6.5 9.5 5 12.5 5 15.5 5 19.3 8 22 12 22z"/>,cash:<><rect x="2.5" y="6" width="19" height="12" rx="2"/><circle cx="12" cy="12" r="2.5"/></>,bolt:<path d="M13 2L4 14h7l-1 8 9-12h-7z"/>,offline:<><path d="M3 3l18 18M8 16.5a5 5 0 017 0M5 12.5a10 10 0 014-2.4M19 12.5a10 10 0 00-2.5-1.8M12 20h.01"/></>,search:<><circle cx="11" cy="11" r="7"/><path d="M20 20l-4-4"/></>,pin:<><path d="M12 21s-7-6-7-11a7 7 0 0114 0c0 5-7 11-7 11z"/><circle cx="12" cy="10" r="2.4"/></>,cup:<><path d="M5 8h10v11a2 2 0 01-2 2H7a2 2 0 01-2-2zM15 11h2.5a2.5 2.5 0 010 5H15"/></>};return <svg viewBox="0 0 24 24" aria-hidden="true">{p[name]}</svg>}
