# Generated by Django 5.2.17 on 2026-10-07 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0003_access_invalidation_event'),
        ('ledger', '0004_payment_confirmation_timestamp_invariant'),
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_points', to='access.deviceregistration')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_points', to='venue.venue')),
            ],
        ),
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COUNTING', 'Counting'), ('CLOSED', 'Closed')], default='OPEN', max_length=12)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('opening_float_cents', models.PositiveIntegerField(default=0)),
                ('opening_idempotency_key', models.CharField(max_length=120)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('counted_amount_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_amount_cents_snapshot', models.IntegerField(blank=True, null=True)),
                ('discrepancy_cents', models.IntegerField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('PENDING', 'Pending'), ('REVIEWED', 'Reviewed')], default='NOT_REQUIRED', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.CharField(blank=True, max_length=240)),
                ('version', models.PositiveIntegerField(default=1)),
                ('cash_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='cash.cashpoint')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts_closed', to='access.staffmember')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts_opened', to='access.staffmember')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts_reviewed', to='access.staffmember')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts', to='venue.venue')),
            ],
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('OPENING_FLOAT', 'Opening float'), ('CASH_PAYMENT', 'Cash payment'), ('CASH_REFUND', 'Cash refund'), ('SUPPLY', 'Supply'), ('WITHDRAWAL', 'Withdrawal'), ('CORRECTION', 'Correction')], max_length=20)),
                ('amount_cents', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('occurred_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('is_post_close_correction', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='access.staffmember')),
                ('actor_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='access.staffsession')),
                ('correction_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='cash.cashmovement')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='access.deviceregistration')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movement', to='ledger.payment')),
                ('refund', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movement', to='ledger.refund')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='cash.cashshift')),
            ],
        ),
        migrations.CreateModel(
            name='CashTenderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due_cents', models.PositiveIntegerField()),
                ('amount_tendered_cents', models.PositiveIntegerField()),
                ('change_given_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cash_tender_detail', to='ledger.payment')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_tenders', to='cash.cashshift')),
            ],
        ),
        migrations.AddIndex(
            model_name='cashpoint',
            index=models.Index(fields=['venue', 'active'], name='cash_point_venue_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashpoint',
            constraint=models.UniqueConstraint(fields=('venue', 'label'), name='cash_point_venue_label_unique'),
        ),
        migrations.AddIndex(
            model_name='cashshift',
            index=models.Index(fields=['venue', 'business_date'], name='cash_shift_venue_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cashshift',
            index=models.Index(fields=['cash_point', 'status'], name='cash_shift_point_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashshift',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('OPEN', 'COUNTING'))), fields=('cash_point',), name='cash_one_active_shift_per_point'),
        ),
        migrations.AddConstraint(
            model_name='cashshift',
            constraint=models.UniqueConstraint(fields=('cash_point', 'opening_idempotency_key'), name='cash_shift_opening_idempotency_unique'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['shift', 'recorded_at'], name='cash_move_shift_recorded_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['shift', 'kind'], name='cash_move_shift_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0), ('amount_cents__lt', 0), _connector='OR'), name='cash_movement_amount_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.UniqueConstraint(fields=('shift', 'idempotency_key'), name='cash_movement_shift_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='cashtenderdetail',
            constraint=models.CheckConstraint(condition=models.Q(('amount_tendered_cents__gte', models.F('change_given_cents'))), name='cash_tender_change_not_exceed_tender'),
        ),
    ]
