# Generated by Django 5.2.17 on 2026-10-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_access_invalidation_event'),
        ('cash', '0001_initial'),
        ('ledger', '0004_payment_confirmation_timestamp_invariant'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_cents__gt', 0), ('kind__in', ('OPENING_FLOAT', 'CASH_PAYMENT', 'SUPPLY'))), models.Q(('amount_cents__lt', 0), ('kind__in', ('CASH_REFUND', 'WITHDRAWAL'))), ('kind', 'CORRECTION'), _connector='OR'), name='cash_movement_kind_direction'),
        ),
    ]
