# Generated by Django 5.2.17 on 2026-10-08 20:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("access", "0003_access_invalidation_event"),
        ("ordering", "0002_order_idempotency"),
        ("venue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("display_name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("notes", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LimitOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("previous_limit_cents", models.PositiveIntegerField()),
                ("limit_cents", models.PositiveIntegerField()),
                ("reason", models.CharField(max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("idempotency_key", models.CharField(max_length=120)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="access.staffmember"
                    ),
                ),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="limit_overrides",
                        to="ordering.tab",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tab", "idempotency_key"), name="house_override_idempotent"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("VISITOR", "Visitante"),
                            ("KNOWN", "Conhecido"),
                            ("REGULAR", "Regular"),
                            ("HOUSE", "Da casa"),
                            ("RESTRICTED", "Restrito"),
                        ],
                        default="KNOWN",
                        max_length=16,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="house_account.customer"
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="venue.venue"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("venue", "customer"), name="house_relationship_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VenueRelationshipPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("VISITOR", "Visitante"),
                            ("KNOWN", "Conhecido"),
                            ("REGULAR", "Regular"),
                            ("HOUSE", "Da casa"),
                            ("RESTRICTED", "Restrito"),
                        ],
                        max_length=16,
                    ),
                ),
                ("limit_cents", models.PositiveIntegerField()),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="venue.venue"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("venue", "kind"), name="house_policy_unique")
                ],
            },
        ),
    ]
