# Generated by Django 5.2.17 on 2026-10-07 17:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0003_access_invalidation_event'),
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='charge', to='ordering.orderitem')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='ordering.tab')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('PIX', 'Pix'), ('OTHER', 'Other')], max_length=12)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to='access.staffmember')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ordering.tab')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tab', 'idempotency_key'), name='ledger_payment_tab_key_unique')],
            },
        ),
    ]
