# Generated by Django 5.2.17 on 2026-10-08 02:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_access_invalidation_event'),
        ('ledger', '0004_payment_confirmation_timestamp_invariant'),
        ('ordering', '0002_order_idempotency'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('ORDER_ITEM_CANCELLATION', 'Order item cancellation')], max_length=40)),
                ('amount_cents', models.IntegerField()),
                ('idempotency_key', models.CharField(max_length=120)),
                ('reason_code', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_adjustments_created', to='access.staffmember')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_adjustments', to='ordering.orderitem')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_adjustments', to='ordering.tab')),
            ],
            options={
                'indexes': [models.Index(fields=['tab', 'created_at'], name='ledger_adjustment_tab_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('tab', 'idempotency_key'), name='ledger_adjustment_tab_key_unique'), models.UniqueConstraint(fields=('order_item', 'kind'), name='ledger_adjustment_item_kind_unique'), models.CheckConstraint(condition=models.Q(('amount_cents__lt', 0), ('kind', 'ORDER_ITEM_CANCELLATION')), name='ledger_adjustment_cancellation_negative')],
            },
        ),
    ]
