# Generated by Django 5.2.17 on 2026-10-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_access_invalidation_event'),
        ('ledger', '0005_correction_financial_reversal'),
        ('ordering', '0002_order_idempotency'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ledgeradjustment',
            name='ledger_adjustment_cancellation_negative',
        ),
        migrations.AlterField(
            model_name='ledgeradjustment',
            name='kind',
            field=models.CharField(choices=[('ORDER_ITEM_CANCELLATION', 'Order item cancellation'), ('COURTESY_REPLACEMENT', 'Courtesy replacement')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='ledgeradjustment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_cents__lt', 0), ('kind', 'ORDER_ITEM_CANCELLATION')), models.Q(('amount_cents__lt', 0), ('kind', 'COURTESY_REPLACEMENT')), _connector='OR'), name='ledger_adjustment_negative_supported_kind'),
        ),
    ]
