# Generated by Django 5.2.17 on 2026-10-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_access_invalidation_event'),
        ('ledger', '0006_remove_ledgeradjustment_ledger_adjustment_cancellation_negative_and_more'),
        ('ordering', '0003_tab_action_reasons_tab_customer_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_payment_id', ''), _negated=True), fields=('provider', 'provider_payment_id'), name='ledger_provider_reference_unique'),
        ),
    ]
