# Generated by Django 5.2.17 on 2026-10-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_payment_ledger_provider_reference_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('AUTHORIZED', 'Authorized'), ('CONFIRMATION_PENDING', 'Confirmation pending'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('PARTIALLY_REFUNDED', 'Partially refunded'), ('REFUNDED', 'Refunded')], default='CONFIRMED', max_length=24),
        ),
    ]
