# Generated by Django 5.2.17 on 2026-10-09 13:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_access_invalidation_event'),
        ('ledger', '0008_alter_payment_status'),
        ('ordering', '0006_orderitem_customization_snapshot_and_more'),
        ('venue', '0002_venue_business_day_cutoff_hour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.IntegerField()),
                ('basis_cents', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PricingApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('command', models.JSONField()),
                ('preview', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingPolicy',
            fields=[
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='venue.venue')),
                ('version', models.PositiveIntegerField(default=1)),
                ('service_enabled', models.BooleanField(default=False)),
                ('service_basis_points', models.PositiveIntegerField(default=0)),
                ('service_max_basis_points', models.PositiveIntegerField(default=10000)),
                ('service_opt_out', models.BooleanField(default=False)),
                ('service_treatment', models.CharField(choices=[('REVENUE', 'Revenue'), ('PASS_THROUGH', 'Pass through')], default='PASS_THROUGH', max_length=16)),
                ('service_refundable', models.BooleanField(default=True)),
                ('staff_discount_basis_points', models.PositiveIntegerField(default=0)),
                ('cashier_discount_basis_points', models.PositiveIntegerField(default=1000)),
                ('maximum_discount_basis_points', models.PositiveIntegerField(default=10000)),
                ('allow_post_payment', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='ledgeradjustment',
            name='ledger_adjustment_item_kind_unique',
        ),
        migrations.RemoveConstraint(
            model_name='ledgeradjustment',
            name='ledger_adjustment_negative_supported_kind',
        ),
        migrations.AddField(
            model_name='ledgeradjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricing_approved', to='access.staffmember'),
        ),
        migrations.AddField(
            model_name='ledgeradjustment',
            name='basis_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ledgeradjustment',
            name='calculation_type',
            field=models.CharField(default='DERIVED', max_length=12),
        ),
        migrations.AddField(
            model_name='ledgeradjustment',
            name='policy_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='ledgeradjustment',
            name='reason_text',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='ledgeradjustment',
            name='request_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ledgeradjustment',
            name='requested_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ledgeradjustment',
            name='response',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='ledgeradjustment',
            name='reverses',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='ledger.ledgeradjustment'),
        ),
        migrations.AddField(
            model_name='ledgeradjustment',
            name='scope',
            field=models.CharField(choices=[('CHARGE', 'Charge'), ('TAB', 'Tab')], default='CHARGE', max_length=8),
        ),
        migrations.AlterField(
            model_name='ledgeradjustment',
            name='kind',
            field=models.CharField(choices=[('ITEM_DISCOUNT', 'Item discount'), ('TAB_DISCOUNT', 'Tab discount'), ('COURTESY', 'Courtesy'), ('SERVICE_CHARGE', 'Service charge'), ('SERVICE_CHARGE_REDUCTION', 'Service reduction'), ('REVERSAL', 'Reversal'), ('ORDER_ITEM_CANCELLATION', 'Order item cancellation'), ('COURTESY_REPLACEMENT', 'Courtesy replacement')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ledgeradjustment',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_adjustments', to='ordering.orderitem'),
        ),
        migrations.AddConstraint(
            model_name='ledgeradjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['ORDER_ITEM_CANCELLATION', 'COURTESY_REPLACEMENT'])), fields=('order_item', 'kind'), name='ledger_adjustment_item_kind_unique'),
        ),
        migrations.AddConstraint(
            model_name='ledgeradjustment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_cents__lte', 0), ('kind__in', ['ITEM_DISCOUNT', 'TAB_DISCOUNT', 'COURTESY', 'SERVICE_CHARGE_REDUCTION'])), models.Q(('amount_cents__gte', 0), ('kind', 'SERVICE_CHARGE')), models.Q(('kind', 'REVERSAL'), ('reverses__isnull', False)), models.Q(('amount_cents__lt', 0), ('kind', 'ORDER_ITEM_CANCELLATION')), models.Q(('amount_cents__lt', 0), ('kind', 'COURTESY_REPLACEMENT')), _connector='OR'), name='ledger_adjustment_negative_supported_kind'),
        ),
        migrations.AddField(
            model_name='adjustmentallocation',
            name='adjustment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='ledger.ledgeradjustment'),
        ),
        migrations.AddField(
            model_name='adjustmentallocation',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_allocations', to='ledger.charge'),
        ),
        migrations.AddField(
            model_name='pricingapproval',
            name='adjustment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.ledgeradjustment'),
        ),
        migrations.AddField(
            model_name='pricingapproval',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.staffsession'),
        ),
        migrations.AddField(
            model_name='pricingapproval',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordering.tab'),
        ),
        migrations.AddConstraint(
            model_name='adjustmentallocation',
            constraint=models.UniqueConstraint(fields=('adjustment', 'charge'), name='pricing_allocation_charge_unique'),
        ),
        migrations.AddConstraint(
            model_name='pricingapproval',
            constraint=models.UniqueConstraint(fields=('tab', 'idempotency_key'), name='pricing_approval_key_unique'),
        ),
    ]
