# Generated by Django 5.2.17 on 2026-10-09 13:36

import hashlib
import json

from django.db import migrations, models


def backfill_settlement_owners(apps, schema_editor):
    Payment = apps.get_model("ledger", "Payment")
    Attempt = apps.get_model("payment_provider", "PaymentAttempt")
    database = schema_editor.connection.alias
    for payment in (
        Payment.objects.using(database)
        .filter(provider__startswith="sumup:", confirmed_at__isnull=False)
        .iterator()
    ):
        attempt = (
            Attempt.objects.using(database)
            .filter(payment_id=payment.pk)
            .order_by("started_at", "id")
            .last()
        )
        metadata = attempt.metadata if attempt else {}
        transaction_id = metadata.get("transaction_id")
        merchant_code = metadata.get("merchant_code")
        if transaction_id and merchant_code:
            key = hashlib.sha256(
                json.dumps(["sumup", merchant_code, transaction_id], separators=(",", ":")).encode()
            ).hexdigest()
            Payment.objects.using(database).filter(pk=payment.pk).update(
                provider_settlement_key=key
            )


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0003_access_invalidation_event"),
        ("ledger", "0008_alter_payment_status"),
        ("payment_provider", "0003_providerrefundrequest"),
        ("ordering", "0006_orderitem_customization_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="provider_settlement_key",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(backfill_settlement_owners, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_settlement_key", ""), _negated=True),
                fields=("provider_settlement_key",),
                name="ledger_provider_settlement_unique",
            ),
        ),
    ]
