# Generated by Django 5.2.17 on 2026-10-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_pricing_history_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingpolicy',
            name='service_removal_requires_manager',
            field=models.BooleanField(default=True),
        ),
    ]
