# Generated by Django 5.2.17 on 2026-10-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('current_price_cents', models.PositiveIntegerField()),
                ('fulfillment_station', models.CharField(choices=[('BAR', 'Bar'), ('KITCHEN', 'Cozinha'), ('NONE', 'Sem preparo')], default='BAR', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
