# ruff: noqa: RUF012
# Django/DRF class-level configuration follows the framework contract.
# Generated by Django 5.2.17 on 2026-10-09 13:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("access", "0003_access_invalidation_event"),
        ("ordering", "0006_orderitem_customization_snapshot_and_more"),
        ("venue", "0002_venue_business_day_cutoff_hour_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrinterEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                (
                    "adapter",
                    models.CharField(
                        choices=[
                            ("BROWSER", "Browser"),
                            ("FILE", "File"),
                            ("NETWORK", "Network"),
                            ("SPOOL", "Spool"),
                        ],
                        max_length=16,
                    ),
                ),
                ("connection_ref", models.SlugField(blank=True, max_length=80)),
                ("width_mm", models.PositiveSmallIntegerField(default=80)),
                ("cut_supported", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                ("health", models.CharField(default="UNKNOWN", max_length=16)),
                ("health_at", models.DateTimeField(null=True)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="venue.venue"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrintJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=120)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENDING", "Sending"),
                            ("FAILED_RETRYABLE", "Failed Retryable"),
                            ("FAILED_FINAL", "Failed Final"),
                            ("DELIVERY_UNCERTAIN", "Delivery Uncertain"),
                            ("SPOOL_ACCEPTED", "Spool Accepted"),
                            ("OUTPUT_READY", "Output Ready"),
                            ("PRINTED", "Printed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="QUEUED",
                        max_length=32,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=240)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("available_at", models.DateTimeField()),
                ("lease_until", models.DateTimeField(null=True)),
                ("attempt_token", models.UUIDField(null=True)),
                ("last_error", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents_printing.printerendpoint",
                    ),
                ),
                (
                    "reprint_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents_printing.printjob",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="access.staffmember"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrintAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token", models.UUIDField(unique=True)),
                ("number", models.PositiveIntegerField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("outcome", models.CharField(blank=True, max_length=32)),
                ("detail", models.CharField(blank=True, max_length=240)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="documents_printing.printjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("kind", models.CharField(max_length=32)),
                ("station", models.CharField(blank=True, max_length=16)),
                ("source_id", models.UUIDField()),
                ("source_version", models.CharField(max_length=64)),
                ("template_version", models.PositiveIntegerField(default=1)),
                ("snapshot", models.JSONField()),
                ("snapshot_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="access.staffmember"
                    ),
                ),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="ordering.tab"
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="venue.venue"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="printjob",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="documents_printing.receiptdocument",
            ),
        ),
        migrations.CreateModel(
            name="StationPrinterBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "station",
                    models.CharField(
                        choices=[("BAR", "Bar"), ("KITCHEN", "Kitchen")], max_length=16
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bindings",
                        to="documents_printing.printerendpoint",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="printerendpoint",
            constraint=models.CheckConstraint(
                condition=models.Q(("width_mm__in", (58, 80))), name="printing_width_supported"
            ),
        ),
        migrations.AddConstraint(
            model_name="printattempt",
            constraint=models.UniqueConstraint(
                fields=("job", "number"), name="printing_attempt_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="receiptdocument",
            constraint=models.UniqueConstraint(
                fields=("venue", "kind", "source_id", "station", "source_version"),
                name="printing_document_source_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="printjob",
            index=models.Index(fields=["state", "available_at"], name="printing_due_idx"),
        ),
        migrations.AddConstraint(
            model_name="printjob",
            constraint=models.UniqueConstraint(
                fields=("endpoint", "idempotency_key"), name="printing_job_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="printjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reprint_of__isnull", True)),
                fields=("document", "endpoint"),
                name="printing_initial_job_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="stationprinterbinding",
            constraint=models.UniqueConstraint(
                fields=("endpoint", "station"), name="printing_binding_unique"
            ),
        ),
    ]
