# ruff: noqa: RUF012
# Django/DRF class-level configuration follows the framework contract.
# Generated by Django 5.2.17 on 2026-10-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents_printing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="printerendpoint",
            name="bridge_seen_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="printjob",
            name="initial_production_key",
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
