# ruff: noqa: RUF012
# Django/DRF class-level configuration follows the framework contract.
# Generated by Django 5.2.17 on 2026-10-09 13:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0003_access_invalidation_event"),
        ("documents_printing", "0002_printerendpoint_bridge_seen_at_and_more"),
        ("guest_access", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptdocument",
            name="created_guest_session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="guest_access.guestsession",
            ),
        ),
        migrations.AlterField(
            model_name="receiptdocument",
            name="created_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="access.staffmember"
            ),
        ),
        migrations.CreateModel(
            name="ReceiptAccessToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="access.staffmember"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents_printing.receiptdocument",
                    ),
                ),
            ],
        ),
    ]
