# Generated by Django 5.2.17 on 2026-10-06 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0002_order_idempotency_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('VISITOR', 'Visitor'), ('KNOWN', 'Known'), ('REGULAR', 'Regular'), ('HOUSE', 'House'), ('RESTRICTED', 'Restricted')], default='VISITOR', max_length=12)),
                ('nickname', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships', to='customers.customer')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships', to='pos.venue')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('customer', 'venue'), name='one_relationship_per_customer_venue')],
            },
        ),
        migrations.CreateModel(
            name='VenueRelationshipPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('VISITOR', 'Visitor'), ('KNOWN', 'Known'), ('REGULAR', 'Regular'), ('HOUSE', 'House'), ('RESTRICTED', 'Restricted')], max_length=12)),
                ('operating_limit_cents', models.PositiveIntegerField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationship_policies', to='pos.venue')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('venue', 'status'), name='one_policy_per_venue_status')],
            },
        ),
    ]
