# Generated by Django 5.2.17 on 2026-10-06 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('STAFF', 'Staff'), ('CASHIER', 'Cashier'), ('MANAGER', 'Manager'), ('OWNER', 'Owner')], default='STAFF', max_length=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REQUIRES_ACTION', 'Requires action'), ('SETTLING', 'Settling'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_tabs', to='pos.staffmember')),
                ('service_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabs', to='pos.servicepoint')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabs', to='pos.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed')], default='DRAFT', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.staffmember')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='pos.tab')),
            ],
        ),
        migrations.AddField(
            model_name='staffmember',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='pos.venue'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_points', to='pos.venue'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='pos.venue')),
            ],
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_points', to='pos.zone'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('fulfillment_station', models.CharField(blank=True, max_length=16)),
                ('state', models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('PICKED_UP', 'Picked up'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('preparing_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pos.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='item_quantity_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('venue', 'name'), name='unique_zone_name_per_venue'),
        ),
        migrations.AddConstraint(
            model_name='servicepoint',
            constraint=models.UniqueConstraint(fields=('venue', 'code'), name='unique_service_point_per_venue'),
        ),
    ]
