# Generated by Django 5.2.17 on 2026-10-06 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('pos', '0002_order_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tabs', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='tab',
            name='limit_overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tab',
            name='limit_overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_overrides', to='pos.staffmember'),
        ),
        migrations.AddField(
            model_name='tab',
            name='limit_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tab',
            name='operating_limit_cents',
            field=models.PositiveIntegerField(default=3000),
        ),
    ]
