# Generated by Django 5.2.17 on 2026-10-06 16:19

import django.db.models.deletion
import pos.models
from django.db import migrations, models


def populate_public_tokens(apps, schema_editor):
    Tab = apps.get_model('pos', 'Tab')
    for tab in Tab.objects.filter(public_token__isnull=True):
        tab.public_token = pos.models.opaque_token()
        tab.save(update_fields=['public_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_tab_customer_tab_limit_overridden_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='public_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.RunPython(
            code=populate_public_tokens,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='tab',
            name='public_token',
            field=models.CharField(default=pos.models.opaque_token, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='PhysicalTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('public_id', models.CharField(default=pos.models.public_table_id, max_length=32, unique=True)),
                ('is_temporary', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('NEEDS_CLEANING', 'Needs cleaning')], default='AVAILABLE', max_length=16)),
                ('x', models.PositiveSmallIntegerField(default=50)),
                ('y', models.PositiveSmallIntegerField(default=50)),
                ('cleaning_started_at', models.DateTimeField(blank=True, null=True)),
                ('cleaned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_point', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_table', to='pos.servicepoint')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_tables', to='pos.venue')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_tables', to='pos.zone')),
            ],
            options={
                'ordering': ['zone__name', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=pos.models.opaque_token, max_length=64, unique=True)),
                ('guest_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('tab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_sessions', to='pos.tab')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_sessions', to='pos.venue')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_sessions', to='pos.physicaltable')),
            ],
        ),
        migrations.AddField(
            model_name='tab',
            name='physical_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabs', to='pos.physicaltable'),
        ),
        migrations.CreateModel(
            name='TableAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=pos.models.opaque_token, max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='pos.physicaltable')),
            ],
        ),
        migrations.AddConstraint(
            model_name='physicaltable',
            constraint=models.UniqueConstraint(fields=('venue', 'label'), name='unique_table_label_per_venue'),
        ),
    ]
