# Generated by Django 5.2.17 on 2026-10-07 16:45

import django.db.models.deletion
import pos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_tab_public_token_physicaltable_customersession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='StaffSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=pos.models.opaque_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='pos.staffmember')),
            ],
        ),
    ]
