# Generated by Django 5.2.17 on 2026-10-08 23:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0003_access_invalidation_event"),
        ("ledger", "0008_alter_payment_status"),
        ("payment_provider", "0001_initial"),
        ("venue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(max_length=24)),
                ("merchant_code", models.CharField(max_length=80)),
                ("active", models.BooleanField(default=True)),
                ("simulated", models.BooleanField(default=False)),
                ("capabilities", models.JSONField(default=dict)),
                ("encrypted_credentials", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(null=True)),
                ("scopes", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("disconnected_at", models.DateTimeField(null=True)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="venue.venue"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("authorized_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="access.deviceregistration"
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="access.staffmember"
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payment_provider.merchantconnection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OAuthAuthorization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("state_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(null=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="access.staffmember"
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="venue.venue"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimulatedTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("status", models.CharField(default="PENDING", max_length=24)),
                ("scenario", models.CharField(default="success", max_length=24)),
                ("lookup_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="ledger.payment"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="merchantconnection",
            constraint=models.UniqueConstraint(
                fields=("venue", "provider", "merchant_code"), name="payprov_merchant_venue_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="deviceauthorization",
            constraint=models.UniqueConstraint(
                fields=("connection", "device", "staff"), name="payprov_device_operator_unique"
            ),
        ),
    ]
