# Generated by Django 5.2.17 on 2026-10-08 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0008_alter_payment_status"),
        ("payment_provider", "0002_merchantconnection_deviceauthorization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderRefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("transaction_id", models.CharField(max_length=160)),
                ("baseline_event_ids", models.JSONField(default=list)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "refund",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="ledger.refund"
                    ),
                ),
            ],
        ),
    ]
