# Generated by Django 5.2.17 on 2026-10-06 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0002_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.IntegerField(help_text='Signed effect on exposure')),
                ('type', models.CharField(choices=[('COURTESY', 'Courtesy'), ('CORRECTION', 'Correction'), ('REVERSAL', 'Reversal')], max_length=12)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='cash.cashshift')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.staffmember')),
                ('order_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_adjustment', to='pos.orderitem')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='pos.tab')),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='charge', to='pos.orderitem')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='pos.tab')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('PIX', 'Pix'), ('CARD', 'Card'), ('CASH', 'Cash'), ('OTHER', 'Other')], max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='CONFIRMED', max_length=12)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cash_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cash.cashshift')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.staffmember')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='pos.tab')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('tab', 'idempotency_key'), name='unique_payment_command_per_tab')],
            },
        ),
    ]
