# Generated by Django 5.2.17 on 2026-10-06 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        ('pos', '0004_tab_public_token_physicaltable_customersession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('PIX', 'Pix'), ('CARD', 'Card'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='CARD', max_length=8)),
                ('provider', models.CharField(max_length=32)),
                ('provider_reference', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=12)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intent', to='ledger.payment')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='pos.tab')),
            ],
        ),
    ]
