# Generated by Django 5.2.18 on 2026-10-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='business_day_cutoff_hour',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.CheckConstraint(condition=models.Q(('business_day_cutoff_hour__lte', 23)), name='venue_cutoff_valid_hour'),
        ),
    ]
