# Generated by Django 5.2.17 on 2026-10-09 17:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_access_invalidation_event'),
        ('venue', '0002_venue_business_day_cutoff_hour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_key', models.CharField(max_length=40)),
                ('rule_version', models.PositiveIntegerField()),
                ('subject_id', models.UUIDField()),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('DANGER', 'Danger')], max_length=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=16)),
                ('source', models.JSONField(default=dict)),
                ('first_detected_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(null=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('acknowledged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='access.staffmember')),
                ('repeat_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='venue.operationalalert')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venue.venue')),
            ],
        ),
        migrations.CreateModel(
            name='OperationalAlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=24)),
                ('occurred_at', models.DateTimeField()),
                ('metadata', models.JSONField(default=dict)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='venue.operationalalert')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OperationalAlertPolicy',
            fields=[
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='venue.venue')),
                ('version', models.PositiveIntegerField(default=1)),
                ('fulfillment_warning_seconds', models.PositiveIntegerField(default=600)),
                ('fulfillment_danger_seconds', models.PositiveIntegerField(default=1200)),
                ('payment_pending_seconds', models.PositiveIntegerField(default=300)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('fulfillment_warning_seconds__gt', 0), ('fulfillment_danger_seconds__gt', models.F('fulfillment_warning_seconds'))), name='venue_alert_sla_ordered')],
            },
        ),
        migrations.AddIndex(
            model_name='operationalalert',
            index=models.Index(fields=['venue', 'status'], name='venue_alert_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='operationalalert',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'RESOLVED'), _negated=True), fields=('venue', 'rule_key', 'subject_id'), name='venue_alert_active_unique'),
        ),
    ]
