# Generated by Django 5.2.17 on 2026-10-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_modifiergroup_modifieroption_productmodifiergroup_and_more'),
        ('venue', '0003_operationalalert_operationalalertevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalalertpolicy',
            name='strategic_products',
            field=models.ManyToManyField(blank=True, to='catalog.product'),
        ),
    ]
