# Generated by Django 5.2.17 on 2026-10-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_modifiergroup_modifieroption_productmodifiergroup_and_more'),
        ('venue', '0004_operationalalertpolicy_strategic_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalalertpolicy',
            name='guest_request_danger_seconds',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='operationalalertpolicy',
            name='guest_request_warning_seconds',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddConstraint(
            model_name='operationalalertpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('guest_request_warning_seconds__gt', 0), ('guest_request_danger_seconds__gt', models.F('guest_request_warning_seconds'))), name='venue_alert_guest_sla_ordered'),
        ),
    ]
