# Generated by Django 5.2.17 on 2026-10-08 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("venue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VenueStream",
            fields=[
                (
                    "venue",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="venue.venue",
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField()),
                ("event_type", models.CharField(max_length=120)),
                ("aggregate_type", models.CharField(max_length=80)),
                ("aggregate_id", models.CharField(max_length=80)),
                ("tab_id", models.UUIDField(null=True)),
                ("payload", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(null=True)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="venue.venue"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["venue", "sequence"], name="realtime_ou_venue_i_6deb77_idx"
                    ),
                    models.Index(
                        fields=["published_at", "id"], name="realtime_ou_publish_db8d09_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("venue", "sequence"), name="realtime_venue_sequence"
                    )
                ],
            },
        ),
    ]
