# Generated by Django 5.2.17 on 2026-10-06 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0003_tab_customer_tab_limit_overridden_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SERVICE_REQUEST', 'Service request'), ('DELIVERY', 'Delivery'), ('BILL_REQUEST', 'Bill request'), ('EXCEPTION', 'Exception')], max_length=20)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('CLAIMED', 'Claimed'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=12)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_tasks', to='pos.staffmember')),
                ('order_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_task', to='pos.orderitem')),
                ('service_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_tasks', to='pos.servicepoint')),
                ('tab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_tasks', to='pos.tab')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_tasks', to='pos.venue')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_tasks', to='pos.zone')),
            ],
            options={
                'ordering': ['-priority', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DispatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_events', to='pos.venue')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='dispatch.dispatchtask')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_runs', to='pos.staffmember')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_runs', to='pos.venue')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_runs', to='pos.zone')),
                ('tasks', models.ManyToManyField(related_name='runs', to='dispatch.dispatchtask')),
            ],
        ),
    ]
